In [10]:
import torch
from torch.autograd import Variable

In [11]:
x = Variable(torch.Tensor([2]), requires_grad=True)
z = (x + 2) ** 2 + 3
print(z)

tensor([19.], grad_fn=<AddBackward0>)


In [12]:
z.backward()
print(x.grad)

tensor([8.])


In [13]:
x = Variable(torch.randn(10, 20), requires_grad=True)
y = Variable(torch.randn(10, 5), requires_grad=True)
w = Variable(torch.randn(20, 5), requires_grad=True)
out = torch.mean(y - torch.matmul(x, w))
out.backward()

In [14]:
print(x.grad.shape)

torch.Size([10, 20])


In [15]:
print(y.grad.shape)

In [16]:
print(w.grad.shape)

torch.Size([20, 5])


In [17]:
m = Variable(torch.FloatTensor([[2, 3]]), requires_grad=True)  
n = Variable(torch.zeros(1, 2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [18]:
n[0, 0] = m[0, 0] ** 2
n[0, 1] = m[0, 1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [19]:
n_like = torch.ones_like(n)
n.backward(n_like)
print(m.grad)
print(n_like)

tensor([[ 4., 27.]])
tensor([[1., 1.]])


In [20]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x ** 2 + x * 2 + 3
print(y)

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

tensor([18.], grad_fn=<AddBackward0>)
tensor([8.])
tensor([16.])
tensor([24.])


In [21]:
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)
k = Variable(torch.zeros(2))

k[0] = x[0] ** 2 + 3 * x[1]
k[1] = x[1] ** 2 + 2 * x[0]
print(k)

tensor([13., 13.], grad_fn=<CopySlices>)


In [22]:
k.backward(torch.FloatTensor([1, 0]), retain_graph=True)
print(x.grad.data)

x.grad.data.zero_()

k.backward(torch.FloatTensor([0, 1]))
print(x.grad.data)

tensor([4., 3.])
tensor([2., 6.])
