In [6]:
import torch
from torch.autograd import Variable

In [12]:
x = Variable(torch.Tensor([2]), requires_grad=True)
z = (x + 2) ** 2 + 3
print(z)

tensor([19.], grad_fn=<AddBackward0>)


In [13]:
z.backward()
print(x.grad)

tensor([8.])


In [17]:
x = Variable(torch.randn(10, 20), requires_grad=True)
y = Variable(torch.randn(10, 5), requires_grad=True)
w = Variable(torch.randn(20, 5), requires_grad=True)
out = torch.mean(y - torch.matmul(x, w))
out.backward()

In [18]:
print(x.grad)

tensor([[ 0.0335,  0.0035, -0.0182, -0.0300, -0.0223,  0.0536, -0.0077, -0.0568,
         -0.0042, -0.0575,  0.0162, -0.0175, -0.0638,  0.0564,  0.0106, -0.0327,
          0.0528,  0.0901, -0.0133, -0.0276],
        [ 0.0335,  0.0035, -0.0182, -0.0300, -0.0223,  0.0536, -0.0077, -0.0568,
         -0.0042, -0.0575,  0.0162, -0.0175, -0.0638,  0.0564,  0.0106, -0.0327,
          0.0528,  0.0901, -0.0133, -0.0276],
        [ 0.0335,  0.0035, -0.0182, -0.0300, -0.0223,  0.0536, -0.0077, -0.0568,
         -0.0042, -0.0575,  0.0162, -0.0175, -0.0638,  0.0564,  0.0106, -0.0327,
          0.0528,  0.0901, -0.0133, -0.0276],
        [ 0.0335,  0.0035, -0.0182, -0.0300, -0.0223,  0.0536, -0.0077, -0.0568,
         -0.0042, -0.0575,  0.0162, -0.0175, -0.0638,  0.0564,  0.0106, -0.0327,
          0.0528,  0.0901, -0.0133, -0.0276],
        [ 0.0335,  0.0035, -0.0182, -0.0300, -0.0223,  0.0536, -0.0077, -0.0568,
         -0.0042, -0.0575,  0.0162, -0.0175, -0.0638,  0.0564,  0.0106, -0.0327,
      

In [19]:
print(y.grad)

tensor([[0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200]])


In [20]:
print(w.grad)

tensor([[ 0.0490,  0.0490,  0.0490,  0.0490,  0.0490],
        [ 0.0513,  0.0513,  0.0513,  0.0513,  0.0513],
        [-0.0975, -0.0975, -0.0975, -0.0975, -0.0975],
        [ 0.0448,  0.0448,  0.0448,  0.0448,  0.0448],
        [ 0.0677,  0.0677,  0.0677,  0.0677,  0.0677],
        [-0.0303, -0.0303, -0.0303, -0.0303, -0.0303],
        [-0.0340, -0.0340, -0.0340, -0.0340, -0.0340],
        [ 0.0079,  0.0079,  0.0079,  0.0079,  0.0079],
        [ 0.0291,  0.0291,  0.0291,  0.0291,  0.0291],
        [-0.0128, -0.0128, -0.0128, -0.0128, -0.0128],
        [ 0.0323,  0.0323,  0.0323,  0.0323,  0.0323],
        [-0.0313, -0.0313, -0.0313, -0.0313, -0.0313],
        [-0.1609, -0.1609, -0.1609, -0.1609, -0.1609],
        [-0.1236, -0.1236, -0.1236, -0.1236, -0.1236],
        [-0.0238, -0.0238, -0.0238, -0.0238, -0.0238],
        [ 0.0507,  0.0507,  0.0507,  0.0507,  0.0507],
        [ 0.0587,  0.0587,  0.0587,  0.0587,  0.0587],
        [ 0.0198,  0.0198,  0.0198,  0.0198,  0.0198],
        [-

In [37]:
m = Variable(torch.FloatTensor([[2, 3]]), requires_grad=True)  
n = Variable(torch.zeros(1, 2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [38]:
n[0, 0] = m[0, 0] ** 2
n[0, 1] = m[0, 1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [39]:
n_like = torch.ones_like(n)
n.backward(n_like)
print(m.grad)
print(n_like)

tensor([[ 4., 27.]])
tensor([[1., 1.]])


In [73]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x ** 2 + x * 2 + 3
print(y)

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

y.backward(retain_graph=True)
print(x.grad)

tensor([18.], grad_fn=<AddBackward0>)
tensor([8.])
tensor([16.])
tensor([24.])


In [74]:
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)
k = Variable(torch.zeros(2))

k[0] = x[0] ** 2 + 3 * x[1]
k[1] = x[1] ** 2 + 2 * x[0]
print(k)

tensor([13., 13.], grad_fn=<CopySlices>)


In [75]:
k.backward(torch.FloatTensor([1, 0]), retain_graph=True)
print(x.grad.data)

x.grad.data.zero_()

k.backward(torch.FloatTensor([0, 1]))
print(x.grad.data)

tensor([4., 3.])
tensor([2., 6.])
